project_id = "hhxqmvkzhzrxzlirzlis"

[functions.ingest-lead]
verify_jwt = false

[functions.ingest-call]
verify_jwt = false

[functions.ingest-interaction]
verify_jwt = false

[functions.update-lead]
verify_jwt = false